<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-VFKJ2SC9" failures="0" tests="5" name="SS.LoginPageTest" time="3.564" errors="1" timestamp="2022-06-27T01:05:59 IST" skipped="0">
  <testcase classname="SS.LoginPageTest" name="verifyLoginWithIncorrectCredentials" time="1.130"/>
  <system-out/>
  <testcase classname="SS.LoginPageTest" name="verifyLoginWithNoData" time="0.214"/>
  <system-out/>
  <testcase classname="SS.LoginPageTest" name="verifyLoginWithIncorrectCredentials" time="1.053"/>
  <system-out/>
  <testcase classname="SS.LoginPageTest" name="verifyLoginWithCorrectCredentials" time="0.000">
    <error message="
Method public void SS.LoginPageTest.verifyLoginWithCorrectCredentials(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : getData" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void SS.LoginPageTest.verifyLoginWithCorrectCredentials(java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException requires a @DataProvider named : getData
at org.testng.internal.Parameters.findDataProvider(Parameters.java:526)
at org.testng.internal.Parameters.handleParameters(Parameters.java:763)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:917)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </error>
  </testcase> <!-- verifyLoginWithCorrectCredentials -->
  <system-out/>
  <testcase classname="SS.LoginPageTest" name="verifyLoginWithIncorrectCredentials" time="1.167"/>
  <system-out/>
</testsuite> <!-- SS.LoginPageTest -->
